# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-07 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filetwo',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
